# Generated by Django 6.0.2 on 2026-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
